package com.devexed.dalwit;

/**
 * A statement that inserts rows in a database and returns the keys it generates, if any.
 */
public interface InsertStatement extends Statement {

    /**
     * Execute the statement on the database, returning a cursor over the keys generated by the insertion.
     * @return The cursor over the generated keys.
     * @throws DatabaseException If the statement failed to execute.
     */
    Cursor insert();

}
