package com.devexed.dalwit;

/**
 * A statement that updates rows in a database. In SQL databases this typically includes INSERT, UPDATE, and DELETE
 * statements.
 */
public interface Statement extends ReadonlyStatement {

    /**
     * Execute the statement on the database, returning the number of rows affected.
     * @return The number of rows affected.
     * @throws DatabaseException If the statement failed to execute.
     */
    long update();

    /**
     * Execute the statement on the database.
     * @throws DatabaseException If the statement failed to execute.
     */
    void execute();

    /**
     * Execute the statement on the database, returning a cursor over the keys generated by the insertion.
     * @return The cursor over the generated keys.
     * @throws DatabaseException If the statement failed to execute.
     */
    Cursor insert();

}
